services:
  ib-gateway:
    image: ghcr.io/gnzsnz/ib-gateway:stable
    container_name: ib-gateway
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TWS_SETTINGS_PATH: /home/ibgateway/tws_settings
      TZ: ${TIME_ZONE:-Etc/UTC}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - ./data:/home/ibgateway/tws_settings
    ports:
      - "127.0.0.1:4001:4003"
      - "127.0.0.1:4002:4004"
      - "127.0.0.1:5900:5900"
